spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.19.128:3306/cj?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  redis:
    host: 192.168.19.128
    port: 6379
    password: redis123456
    # 默认数据库
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        min-idle: 0
        max-wait: 10
    timeout: 500